### ISSUE TITLE
Remove Escapable

### ISSUE THREAD

**Issue by sheluchin** [Alonski/MultiSendEthereum#13]
It doesn't look like this contract holds any balances so I don't understand the need to include the escape hatch. It would save on gas and make the contract easier to understand if we could remove the unused parts. I'd be happy to strip it out if it's indeed not necessary. Otherwise, please help me understand why it's there :)

**Comment by Quazia** [comment]
Yeah the contract does not/should not hold fund. Its there just as a safety net in case the contract didn't function ad intended. Now that its had a ton of eth through it removing the hatch is probably fine.

**Comment by Quazia** [comment]
Oh wait, is it an eth or token hatch? There are edge cases where you could get eth/tokens stuck... Always assume somebody will use your contracts wrong 😂😂

**Comment by sheluchin** [comment]
It just inherits from [Escapable.sol](https://github.com/Giveth/common-contract-deps/blob/master/contracts/Escapable.sol) which works as an escape hatch for ETH and tokens (unless blacklisted).

Do you think there's a need for a slimmed-down version of MultiSend that doesn't include the escape hatch, or is it worth keeping around just in case someone does incorrectly send ETH and/or tokens to the contract? It's a bit of a judgement call. 

I think the ideal solution would be to make the `escapeHatchCaller` and `escapeHatchDestination` dynamic per invocation so that the user can decide those params themselves instead of putting the responsibility of distributing the rescued funds to some hardcoded address.

**Comment by Alonski** [comment]
The reason they were hard-coded is that this was built for a specific use case `Giveth payouts`
I think it could make sense to create a base contract without hard-coded caller and destination and then extend that base class into the current contract.
